sudo: false
language: python
os:
  - linux
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"

git:
  depth: 2

cache:
  - pip: true

branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"

env:
  global:
    - GITHUB_REPO=Midnighter/dependency-info

matrix:
  fast_finish: true

install:
  - pip install --upgrade pip setuptools wheel tox tox-travis

script:
  - travis_wait tox

after_success:
  - bash <(curl -f https://codecov.io/bash)

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      install: pip install --upgrade pip setuptools wheel
      script: echo "Deploying..."
      after_success: ignore
      deploy:
        - provider: pypi
          skip_cleanup: true
          distributions: sdist bdist_wheel
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            tags: true
            repo: $GITHUB_REPO
        - provider: releases
          skip_cleanup: true
          api_key: $GITHUB_TOKEN
          body: "Please see https://github.com/${GITHUB_REPO}/blob/${TRAVIS_TAG}/HISTORY.rst for the full release notes."
          on:
            tags: true
            repo: $GITHUB_REPO

notifications:
  email:
    on_success: never
    on_failure: always
    on_pull_requests: false
